import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import UserSync from '@/components/UserSync'
import TanStackProvider from '@/components/providers/TanStackProvider'


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <TanStackProvider>
    <ClerkProvider appearance={{
      variables: {
        colorPrimary: "#6c5ce7",
        colorBackground: "#f3f4f6",
        colorText: "#2f3436",
        colorTextSecondary: "#444444",
        colorInputBackground: "#f3f4f6"
      }
    }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`} >
          <UserSync />
          {children}
        </body>
      </html>
    </ClerkProvider>
    </TanStackProvider>
  )
}